---
- name: add lines to myfile - version 2
  hosts: localhost
  tasks:
    - name: add lines
      blockinfile:
        path: /root/git_repositories/ansible_playbooks1/myfile
        create: yes
        block: |  # add two line
          this is line 1
          this is line 2  